cluster-name = "restate-jepsen"
roles = ["metadata-store", "admin", "worker", "log-server"]
log-filter = "restate_core::network::connection_manager=info,restate_metadata_store::omnipaxos=debug,restate_admin::metadata_api=debug,restate=debug"
#log-filter = "restate_core::network::connection_manager=info,restate_metadata_store::omnipaxos=trace,restate_admin::metadata_api=trace,restate=trace"
log-format = "compact"
rocksdb-total-memory-size = "100 MB"

[admin]
heartbeat-interval = "1s"
default-replication-strategy = "on-all-nodes"

[metadata-store]
type = "omnipaxos"

[metadata-store-client]
#addresses = ["http://n1:5122/", "http://n2:5122/", "http://n3:5122/"]

[bifrost]
default-provider = "replicated"
