cluster-name = "restate-jepsen"
bootstrap-num-partitions = 6
log-filter = "restate_core::network::connection_manager=info,restate=debug"
log-format = "compact"
rocksdb-total-memory-size = "100 MB"

[admin]
heartbeat-interval = "1s"
default-replication-strategy = "on-all-nodes"

[metadata-store-client]
#type = "embedded"
#address = "http://127.0.0.1:5122/"

[bifrost]
default-provider = "replicated"
